version: '2'
services:
  elasticsearch:
    image: elasticsearch
    container_name: elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./esconfig/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./esdata:/etc/elasticsearch/esdata  
    ports:
      - 9200:9200
      - 9300:9300